name: Release

on:
  push:
    branches:
      # TODO delete me
      - multitarget-release-workflow
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      # TODO for testing, set fail-fast to false
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchain for target architecture
      run: rustup target add ${{ matrix.target }}

    # TODO checkout WezTerm repo for how to cache dependencies

    - name: Build
      run: >
        cargo build
        --verbose
        --release
        --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose

    - uses: actions/upload-artifact@v4
      with:
        name: tt-${{ github.ref_name }}-${{ matrix.target }}
        path: |
          target/${{ matrix.target }}/release/main
        if-no-files-found: error
        retention-days: 1
        overwrite: true

  publish:

    needs: build

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

    - uses: actions/download-artifact@v4

    - name: Delete release of same name
      run: gh release delete ${{ github.ref_name }} --yes || true

    - name: testing stuff
      run: tree .

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        ${{ github.ref_name }}
        --title "${{ github.ref_name }} (alpha)"
        --prerelease
        target/x86_64-unknown-linux-musl/release/main
        target/aarch64-apple-darwin/release/main
