name: Release

on:
  push:
    branches:
      # TODO delete me
      - multitarget-release-workflow
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM toolchain
      if: startsWith(${{ matrix.target }}, "aarch64")
      run: rustup target add aarch64-apple-darwin

    # TODO checkout WezTerm repo for how to cache dependencies

    - name: Build
      run: >
        cargo build
        --verbose
        --release
        --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose

    - name: Create release
      run: >
        gh release create
        ${{ github.ref_name }}
        --title "${{ github.ref_name }} (alpha)"
        --prerelease
        target/x86_64-unknown-linux-musl/release/main
        target/aarch64-apple-darwin/release/main
