name: Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install toolchain for target architecture
      run: rustup target add ${{ matrix.target }}

    - name: Cache cargo dependencies
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: >
        cargo build
        --verbose
        --release
        --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose

    - name: Create tarball
      run: |
        mv \
          target/${{ matrix.target }}/release/main \
          tt-${{ github.ref_name }}-${{ matrix.target }}
        tar \
          --create \
          --gzip \
          --file=tt-${{ github.ref_name }}-${{ matrix.target }}.tar.gz \
          tt-${{ github.ref_name }}-${{ matrix.target }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.ref_name }}-${{ matrix.target }}
        path: |
          tt-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
        if-no-files-found: error
        retention-days: 1
        overwrite: true

  publish:

    needs: build

    permissions:
      # For creating a release
      contents: write

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4

    - name: Delete release of same name
      env:
        GH_TOKEN: ${{ github.token }}
      run: gh release delete ${{ github.ref_name }} --yes || true

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        ${{ github.ref_name }}
        --title "${{ github.ref_name }}"
        --notes-file doc/release_notes/${{ github.ref_name }}.md
        ${{ github.ref_name }}-x86_64-unknown-linux-musl/tt-${{ github.ref_name }}-x86_64-unknown-linux-musl.tar.gz
        ${{ github.ref_name }}-aarch64-apple-darwin/tt-${{ github.ref_name }}-aarch64-apple-darwin.tar.gz
