name: Release

on:
  push:
    branches:
      # TODO delete me
      - multitarget-release-workflow
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      # TODO for testing, set fail-fast to false
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    permissions:
      content: write

    steps:
    - uses: actions/checkout@v4

    - name: Install ARM toolchain
      run: rustup target add ${{ matrix.target }}

    # TODO checkout WezTerm repo for how to cache dependencies

    - name: Build
      run: >
        cargo build
        --verbose
        --release
        --target ${{ matrix.target }}

    - name: Run tests
      run: cargo test --verbose

    - name: Create release
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        ${{ github.ref_name }}
        --title "${{ github.ref_name }} (alpha)"
        --prerelease
        target/${{ matrix.target }}/release/main
